#pragma once

#ifndef PAGE_LIBRARY_SCREEN_WIDTH
#define PAGE_LIBRARY_SCREEN_WIDTH 320
#endif
#ifndef PAGE_LIBRARY_SCREEN_HEIGHT
#define PAGE_LIBRARY_SCREEN_HEIGHT 240
#endif

#ifndef PAGE_LIBRARY_BTN_UP
#define PAGE_LIBRARY_BTN_UP 15
#endif
#ifndef PAGE_LIBRARY_BTN_DOWN
#define PAGE_LIBRARY_BTN_DOWN 14
#endif
#ifndef PAGE_LIBRARY_BTN_LEFT
#define PAGE_LIBRARY_BTN_LEFT 16
#endif
#ifndef PAGE_LIBRARY_BTN_RIGHT
#define PAGE_LIBRARY_BTN_RIGHT 5
#endif
#ifndef PAGE_LIBRARY_BTN_OK
#define PAGE_LIBRARY_BTN_OK 17
#endif
